-- CreateTable
CREATE TABLE "Requests" (
    "id" INT4 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "organizationId" STRING NOT NULL,
    "userId" STRING NOT NULL,
    "webhookCall" STRING NOT NULL,

    CONSTRAINT "Requests_pkey" PRIMARY KEY ("id")
);

-- CreateIndex
CREATE UNIQUE INDEX "Requests_organizationId_userId_key" ON "Requests"("organizationId", "userId");
