-- CreateTable
CREATE TABLE "User" (
    "id" INT4 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "uid" STRING NOT NULL,
    "salt" STRING NOT NULL,
    "verifyingKey" STRING NOT NULL,
    "serverEphermalSecret" STRING,
    "serverEphermalPublic" STRING,
    "clientEphermalPublic" STRING,
    "ageVerificationJSON" JSONB,
    "ageProofJSON" JSONB,
    "agePublicJSON" JSONB,

    CONSTRAINT "User_pkey" PRIMARY KEY ("id")
);

-- CreateIndex
CREATE UNIQUE INDEX "User_uid_key" ON "User"("uid");
