/*
  Warnings:

  - You are about to drop the `Requests` table. If the table is not empty, all the data it contains will be lost.

*/
-- DropTable
DROP TABLE "Requests";

-- CreateTable
CREATE TABLE "Request" (
    "id" INT4 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "organizationId" STRING NOT NULL,
    "userId" STRING NOT NULL,
    "webhookCall" STRING NOT NULL,

    CONSTRAINT "Request_pkey" PRIMARY KEY ("id")
);

-- CreateIndex
CREATE UNIQUE INDEX "Request_organizationId_userId_key" ON "Request"("organizationId", "userId");
